version: 1
project:
  name: FixNow
  monorepo: true
review:
  block_on: []
  focus:
    - title: "Multi-Agent Event Integrity"
      guidelines: |
        Each event must include: type, actor, jobId, audience (homeowner|contractor|both),
        and contractorId when relevant. Use a single emitter (pushEvent) and avoid branches
        that skip emission.
checks:
  secrets_exposed:
    enabled: true
