name: Deploy FixNow to GitHub Pages

on:
  push: { branches: [main] }

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install
        working-directory: frontend/contractor-map
        run: npm ci
      - name: Build
        working-directory: frontend/contractor-map
        run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with: { path: frontend/contractor-map/build }

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
